#ifndef Get_HPP
#define Get_HPP

#include "process_request.hpp"

const std::string html_start = "<!DOCTYPE html>\n"
                "<html lang=\"en\">\n"
                "<head>\n"
                "    <meta charset=\"UTF-8\">\n"
                "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                "    <title>Directory Listing</title>\n"
                "    <style>\n"
                "        body {\n"
                "            font-family: Arial, sans-serif;\n"
                "            background-color: #f8f9fa;\n"
                "            color: #343a40;\n"
                "            margin: 0;\n"
                "            padding: 0;\n"
                "        }\n"
                "        .container {\n"
                "            max-width: 600px;\n"
                "            margin: 50px auto;\n"
                "            padding: 30px;\n"
                "            background-color: #fff;\n"
                "            border-radius: 8px;\n"
                "            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n"
                "        }\n"
                "        h1 {\n"
                "            color: #007bff;\n"
                "            text-align: center;\n"
                "            margin-bottom: 20px;\n"
                "        }\n"
                "        ul {\n"
                "            list-style-type: none;\n"
                "            padding: 0;\n"
                "            margin: 0;\n"
                "        }\n"
                "        li {\n"
                "            margin-bottom: 10px;\n"
                "        }\n"
                "        a {\n"
                "            color: #007bff;\n"
                "            text-decoration: none;\n"
                "        }\n"
                "        a:hover {\n"
                "            text-decoration: underline;\n"
                "        }\n"
                "    </style>\n"
                "</head>\n"
                "<body>\n"
                "    <div class=\"container\">\n"
                "        <h1>Directory Listing</h1>\n"
                "        <ul>\n";

const std::string html_end = "</ul>\n"
"    </main>\n"
"\n"
"    <footer>\n"
"        <p>Ce site a été créé par [Votre Nom]</p>\n"
"    </footer>\n"
"</body>\n"
"</html>";

#endif